version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/minu?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3632015jj
      JWT_SECRET: mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForSecurity
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 3632015jj
      MYSQL_DATABASE: minu
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    volumes:
      - C:\Users\SAMSUNG\dnd-13th-3-backend\mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge