spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

app:
  frontend:
    base-url: http://localhost:3000

gemini:
  api:
    key: "AIzaSyD84j8iIE-2_DRpIFuT3qhCmd7inLCZjUQ"